hotwire_dj/hotwire_dj/turbo_drive/urls.py
from django.urls import path
from .views import create_view, list_view

app_name = 'turbo-drive'

urlpatterns = [
    path('create/', create_view, name='task-create'),
    path('list/', list_view, name='task-list'),
]

hotwire_dj/hotwire_dj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="index.html"), name='home'),
    path('turbo-drive/', include('hotwire_dj.turbo_drive.urls')),
    path('admin/', admin.site.urls),
]

hotwire_dj/hotwire_dj/tasks/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MinLengthValidator


class Task(models.Model):
    title = models.CharField(
        max_length=250,
        validators=[MinLengthValidator(limit_value=3)]
    )

    due_date = models.DateField(default=timezone.now)

hotwire_dj/hotwire_dj/turbo_drive/models.py
from django.db import models

# Create your models here.

hotwire_dj/hotwire_dj/tasks/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    title = forms.TextInput(attrs={'class':'border rounded'})

    due_date = forms.DateField(
        widget=forms.TextInput(
            attrs={'type': 'date'}
        )
    )

    class Meta:
        model = Task
        fields = ("title", "due_date")

hotwire_dj/hotwire_dj/tasks/views.py
from django.shortcuts import render

# Create your views here.

hotwire_dj/hotwire_dj/turbo_drive/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from hotwire_dj.tasks.forms import TaskForm

from hotwire_dj.tasks.models import Task


def create_view(request):
    import time
    time.sleep(1)
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Task created successfully')
            return redirect('turbo-drive:task-list')
    else:
        form = TaskForm()
    return render(request, 'turbo_drive/create.html', {'form': form})

def list_view(request):
    object_list=Task.objects.all().order_by('-due_date')
    context = {
        "object_list": object_list,
    }

    return render(request, 'turbo_drive/list.html', context)

hotwire_dj/hotwire_dj/templates/index.html
{% extends "turbo_drive/base.html" %}
{% load webpack_loader static %}
{% block title %} Home {% endblock title %}
{% load crispy_forms_tags %}
{% load tailwind_filters %}
{% block content %}


        <div class="jumbotron py-5 from-pink-500 to-orange-400">
            <div class="w-full max-w-7xl mx-auto px-4 ">

                <h1 class="text-4xl mb-4">Hello, Blessed!</h1>

                    <p class="mb-4">There are three ways to ultimate success: The first way is to be kind. The second way is to be kind. The third way is to be kind.

                <div class="flex justify-center">
                    <img src="{% static 'vendors/images/cfm.png' %}" class="img-fluid"/>
                </div>
            </div>
        </div>

{% endblock %}

hotwire_dj/hotwire_dj/templates/turbo_drive/base.html
{% load webpack_loader static %}
<!DOCTYPE html>
<html lang="">
    <head>
        <meta charset="utf-8" />
        <link rel="icon" type="image/x-icon" href="{% static 'vendors/images/favicon.ico' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>HotDj  | {% block title %}{% endblock title%}</title>

        {% block extra_top_js %}
        {% endblock %}

        {% stylesheet_pack 'turbo_drive' %}
        {% javascript_pack 'turbo_drive' attrs='defer' %}
    </head>
    <body>

        {% include 'turbo_drive/navbar.html' %}
        {% include 'turbo_drive/messages.html' %}

        {% block content %}
        {% endblock content %}

        {% block extra_bottom_js %}
        {% endblock %}

    </body>
</html>

hotwire_dj/hotwire_dj/templates/turbo_drive/create.html
{% extends "turbo_drive/base.html" %}
{% block title %} Create Task{% endblock title %}
{% load crispy_forms_tags %}
{% load tailwind_filters %}

{% block extra_top_js %}
<script>
console.log('top script');
</script>
<script>
console.log('create page top script');
</script>
{% endblock %}

{% block content %}

        <div class="w-full max-w-7xl mx-auto px-4 py-4">
            <div class="grid grid-cols-2 gap-4">
                <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4  rounded-full px-5 py-2.5 mr-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800" value="Submit">Submit</button>

            </form>
            </div>
        </div>

{% endblock %}

{% block extra_bottom_js %}
    <script>
        console.log('create page extra_bottom_js')
    </script>
{% endblock %}

hotwire_dj/hotwire_dj/templates/turbo_drive/list.html
{% extends "turbo_drive/base.html" %}
{% block title %} Task List {% endblock title %}
{% load crispy_forms_tags %}
{% load tailwind_filters %}
{% block content %}

{% block extra_top_js %}
    <script>
        console.log('top script');
    </script>
    <script>
        console.log('list page top script');
    </script>
{% endblock %}

    <div class="w-full max-w-7xl mx-auto px-4">
            <h1 class="text-4xl sm:text-6xl lg:text-7xl mb-6">Task List</h1>
            <div class="md:w-2/3 bg-white rounded-lg border mb-4">
            <ul class="divide-y-2 divide-gray-100" id="task-list-ul">
                {% for instance in object_list %}
            <li class="p-3 flex items-center">
            {{ instance.due_date|date:"Y-m-d" }}: {{ instance.title }}
            </li>
            {% endfor %}
            </ul>
            </div>
    </div>

{% endblock %}

{% block extra_bottom_js %}
    <script>
        console.log('list page extra_bottom_js')
    </script>
{% endblock %}

hotwire_dj/hotwire_dj/templates/turbo_drive/messages.html
{% for message in messages %}
{# data-turbo-cache="false" will tell Turbo to not cache the element #}
    <div data-turbo-cache="false" class="p-4 mb-4 text-sm text-green-700 bg-green-100 rounded-lg dark:bg-green-200 dark:text-green-800" role="alert">
    {{ message|safe }}
    </div>
{% endfor %}

hotwire_dj/hotwire_dj/templates/turbo_drive/navbar.html
{% load webpack_loader static %}
<!--<nav class="flex items-center font-lg justify-between flex-wrap bg-teal-500 p-6 mb-4">-->
<!--    <div class="max-w-6xl mx-auto px-4">-->
<!--        <a href="{% url 'home' %}" class="inline-block mt-0 text-teal-200 hover:text-white mr-4" aria-current="page">-->
<!--                Home-->
<!--        </a>-->
<!--        <a href="{% url 'turbo-drive:task-list' %}" class="inline-block mt-0 text-teal-200 hover:text-white mr-4">-->
<!--                List-->
<!--        </a>-->

<!--        <a href="{% url 'turbo-drive:task-create' %}" class="inline-block mt-0 text-teal-200 hover:text-white mr-4">-->
<!--            Create-->
<!--        </a>-->
<!--    </div>-->
<!--</nav>-->



<nav class="bg-teal-500 shadow-lg">
		<div class="max-w-6xl mx-auto px-4">
			<div class="flex justify-between">
				<div class="flex space-x-7">
					<!-- Website Logo -->
					<div>
						<a href="{% url 'home' %}" class="flex items-center py-4 px-2">
							<img src="{% static 'vendors/images/notepad.png' %}" alt="Logo" class="h-8 w-8 mr-2" />
							<span class="text-xl font-semibold whitespace-nowrap dark:text-white"
								>Tasker</span
							>
						</a>
					</div>
					<!-- Primary Navbar items -->
					<div class="md:flex items-center space-x-1">
						<a
							  {% if '/' in request.path %}
								 class="py-4 px-2 text-teal-200 border-b-4 border-white-200 font-semibold"
							  {% else %}
								 class="py-4 px-2 text-teal-200  border-white-500 font-semibold"
							  {% endif %}

							href="{% url 'home' %}">

							Home</a>

						<a

							{% if 'list' in request.path %}
								 class="py-4 px-2 text-teal-200 border-b-4 border-white-500 font-semibold"
							  {% else %}
								 class="py-4 px-2 text-teal-200  border-white-500 font-semibold"
						    {% endif %}

							href="{% url 'turbo-drive:task-list' %}">

							Task List</a>
						<a

							{% if 'create' in request.path %}
								 class="py-4 px-2 text-teal-200 border-b-4 border-white-500 font-semibold"
							  {% else %}
								 class="py-4 px-2 text-teal-200  border-white-500 font-semibold"
						    {% endif %}

							href="{% url 'turbo-drive:task-create' %}"

							>Create Task</a>

					</div>
				</div>
			</div>
		</div>
	</nav>